//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int Cod_Administrador { get; set; }
        public string Nome_Administrador { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
