//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.PROFESSORs = new HashSet<PROFESSOR>();
        }
    
        public int idAluno { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<System.DateTime> dataUltAtualizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFESSOR> PROFESSORs { get; set; }
    }
}
