//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATIVIDADE
    {
        public int COD_ATIVIDADE { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA_INI { get; set; }
        public System.DateTime DATA_FIM { get; set; }
        public int COD_PROF { get; set; }
        public int COD_MATERIA { get; set; }
        public int COD_TURMA { get; set; }
        public int PERIODO_LETIVO { get; set; }
    
        public virtual PROFMATERIATURMA PROFMATERIATURMA { get; set; }
    }
}
