//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControleAtualiEntities1 : DbContext
    {
        public ControleAtualiEntities1()
            : base("name=ControleAtualiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Aluno> Alunoes { get; set; }
        public virtual DbSet<MATERIA> MATERIAs { get; set; }
        public virtual DbSet<PROFESSOR> PROFESSORs { get; set; }
        public virtual DbSet<Turma> Turmas { get; set; }
    }
}
