//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA
    {
        public int IdMateria { get; set; }
        public string Nome_Materia { get; set; }
        public Nullable<int> IdProfessor { get; set; }
    
        public virtual PROFESSOR PROFESSOR { get; set; }
    }
}
