//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        public int COD_NOTA { get; set; }
        public int COD_ALUNO { get; set; }
        public int COD_PROF { get; set; }
        public int COD_MATERIA { get; set; }
        public int COD_TURMA { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESSOR PROFESSOR { get; set; }
        public virtual TURMA TURMA { get; set; }
    }
}
