//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTA()
        {
            this.ALUNO = new HashSet<ALUNO>();
        }
    
        public int COD_NOTA { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public Nullable<int> COD_MATERIA { get; set; }
        public Nullable<int> COD_TURMA { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESSOR PROFESSOR { get; set; }
        public virtual TURMA TURMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUNO> ALUNO { get; set; }
    }
}
